title: "Won Lee"
subtitle: "A Neuroscientist and Hiker"
email: won.lee@columbia.edu
personal-email: elainewonlee@gmail.com
work-email: won.lee@columbia.edu
description: "Data, brain, physiology, behavior, and data again"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
street_address: "108 Dean Keaton St."
city: "Austin"
state: "TX"
zip_code: 78712
country: "United States of America"
twitter_username: veritasluxmeaWL
github_username:  veritas1uxmea

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
# tiles-count: 4
no_contact_form: true

# social settings
500px_url:
facebook_url:
github_url: https://www.github.com/veritas1uxmea
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/won_inamillion_
linkedin_url: https://www.linkedin.com/in/wonlee-neuroscience
#pinterest_url:
#slack_url:
twitter_url: https://www.twitter.com/veritasluxmeaWL

# Build settings
markdown: kramdown
#theme: minima

sass:
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/